### ISSUE TITLE
Task List for Activity 1

### ISSUE THREAD

**Issue by kbthought** [kbthought/gittest#1]
- [x] Checkout  'more-to-learn'  branch
- [x] Edit the file - index html
- [x] Commit the changes - git commit -am "Modified Index file"
- [x] Rebase 'more-to-learn' onto 'master'
- [x] Push changes to GitHub
- [x] Create a Pull Request
- [x] Mention the training team 
- [x] Get an approval
- [x] Merge the Pull Request
